project:
  type: website
  preview: 
    port: 5001

website:
  search: 
    location: navbar
    type: textbox
  favicon: './shared/favicon.svg'

  navbar:
    background: '#F0F3F5'
    logo: './shared/logo.png'
    left:
      - text: "Overview"
        file: ./index.md
      - text: "Getting Started"
        file: ./getting-started/introduction-page.md
      - text: "Our tools"
        file: ./app/dataset-page.md
      - text: "Walkthroughs"
        file: ./walkthroughs/demo-datasets-page.md
      - text: "REST API"
        file: ./rest-api/overview.qmd
      - text: "Python API docs"
        href: https://docs.openprotein.ai/api-python/index.html
      - text: "Login"
        href: https://app.openprotein.ai/
        target: _blank
      - text: "Contact"
        href: https://www.openprotein.ai/contact
        target: _blank
      
  sidebar:
    - id: main
      background: '#F0F3F5'
      style: "docked"
      collapse-level: 1
      align: left
      contents:
      - section: "Getting Started"
        contents:
          - ./getting-started/get-started-with-no-code.md
          - ./getting-started/get-started-with-our-API.md
          - ./getting-started/account-page.md
      - section: "Our tools"
        contents:
          - section: ./poet/introduction-page.md
            contents:
              - ./poet/defining-prompts-page.md
              - ./poet/scoring-system-log-probability.md
              - ./poet/ensembling.md
              - ./poet/history.md
              - section: Frontend PoET tutorials
                contents: 
                - ./poet/front-end/rank-sequences.md
                - ./poet/front-end/substitution-analysis-poet.md
                - ./poet/front-end/generate-sequences.md
              - section: API PoET tutorials
                contents: 
                - ./poet/api-tutorials/designing-new-enzymes.md
                - ./poet/api-tutorials/substitutions-deletions.md
          - section: Core workflow
            contents:
            - text: Overview
              file: ./core/overview.md
            - ./core/uploading-your-data.md
            - ./core/visualizing-your-data.md
            - text: Scoring and log-likelihood
              file: ./core/core-scoring-log-likelihood.md
            - ./core/navigating-your-projects.md
            - section: Frontend tutorials
              contents: 
                - text: Model training and evaluation
                  file: ./core/front-end/core-model-train-evaluate.md
                - ./core/front-end/predictions-page.md
                - ./core/front-end/design-sequence.md
            - section: API tutorials
              contents: 
                - ./core/api-tutorials/sequence-based-learning.md
                - ./core/api-tutorials/protein-language-models-embeddings.md
                - ./core/api-tutorials/quantitative-decision-making-for-library-design.md
          - section: Structure Prediction
            contents:
              - ./structure-prediction/using-structure-prediction.md
      - ./core/tutorial-examples.md
      - section: "Walkthroughs"
        contents: 
            - ./walkthroughs/anitbody-engineering.md
            - ./walkthroughs/enzyme-engineering.md
      - section: "Resources"
        contents:
            - ./resources/faq.md
            - ./resources/publications.md
            - ./resources/glossary.md
            - ./resources/site-index.md
      - section: "REST API"
        contents:
            - ./rest-api/overview.qmd
            - ./rest-api/authentication-and-jobs.qmd
            - ./rest-api/project.qmd
            - ./rest-api/poet.qmd
            - ./rest-api/embeddings.qmd  

format:
  html:
    theme:
      light: [cosmo, theme.scss]
    toc: true
    grid:
      sidebar-width: 350px
      body-width: 900px
      margin-width: 300px