project:
  type: website
  preview: 
    port: 5001
  resources:
    - "openapi/*"
    - "theme.scss"

website:
  search: 
    location: navbar
    type: textbox
  favicon: './shared/favicon.svg'

  navbar:
    background: '#F0F3F5'
    logo: './shared/logo.png'
    left:
      - text: "Overview"
        file: ./index.md
      - text: "Getting Started"
        file: ./getting-started/get-started-with-no-code.md
      - text: "Our tools"
        file: ./tools/index.md
      - text: "Walkthroughs"
        file: ./walkthroughs/index.md
      - text: "REST API"
        file: ./rest-api/overview.qmd
      - text: "Python API docs"
        href: https://docs.openprotein.ai/api-python/index.html
      - text: "Log in"
        href: https://app.openprotein.ai/
      - text: "Contact"
        href: https://www.openprotein.ai/contact
        
      
  sidebar:
    - id: main
      background: '#F0F3F5'
      style: "docked"
      collapse-level: 1
      align: left
      contents:
      - section: "Getting Started"
        contents:
          - text: Get started with no code
            file: ./getting-started/get-started-with-no-code.md
          - text: Get started with our API
            file: ./getting-started/get-started-with-our-API.md
          - text: Account information
            file: ./getting-started/account-page.md
      - section: Our tools
        file: ./tools/index.md
        contents:
          - section: PoET
            file: ./poet/index.md
            contents:
              - text: Prompt and prompt sampling methods
                file: ./poet/prompts.md
              - text: Scoring system and log probability 
                file: ./poet/scoring-log-likelihood.md
              - ./poet/ensembling.md
              - ./poet/history.md
              - section: Frontend PoET tutorials
                contents: 
                - text: Using the rank sequences tool
                  file: ./poet/rank-sequences.md
                - text: Substitution analysis with PoET
                  file: ./poet/substitution-analysis.md
                - text: Generate sequences
                  file: ./poet/generate-sequences.md
              - section: API PoET tutorials
                contents: 
                - text: Getting started with PoET
                  href: https://docs.openprotein.ai/api-python/demos/poet_demo.html
                - text: Designing new enzymes
                  href: https://docs.openprotein.ai/api-python/demos/chorismate.html
                - text: Substitutions and deletions
                  href: https://docs.openprotein.ai/api-python/demos/AMIE_substitution_deletion_analysis_poet.html         
          - section: Optimization and Prediction Models (OP models)
            file: ./opmodels/index.md
            contents:
              - text: Overview
                file: ./opmodels/overview.md
              - ./opmodels/uploading-your-data.md
              - text: Scoring and log-likelihood
                file: ./opmodels/scoring-log-likelihood.md
              - ./opmodels/navigating-your-projects.md
              - section: Frontend tutorials
                contents: 
                - ./opmodels/visualization.md
                - text: Model training and evaluation
                  file: ./opmodels/model-train-evaluate.md
                - ./opmodels/sub-analysis.md
                - ./opmodels/design.md
              - section: API tutorials
                contents: 
                  - text: Getting started with sequence-based learning
                    href: https://docs.openprotein.ai/api-python/demos/core_demo.html
                  - text: Getting started with embeddings
                    href: https://docs.openprotein.ai/api-python/demos/embedding_demo.html
              - ./opmodels/quantitative-decision-making-for-library-design.md
      - section: Structure Prediction
        contents:
          - ./structure-prediction/using-structure-prediction.md
      - text: Tutorials and Examples
        file: ./tutorials/index.md
      - section: "Walkthroughs"
        file: ./walkthroughs/index.md
        contents: 
            - ./walkthroughs/anitbody-engineering.md
            - ./walkthroughs/enzyme-engineering.md
      - section: "REST API"
        contents:
            - ./rest-api/overview.qmd
            - ./rest-api/authentication-and-jobs.qmd
            - ./rest-api/project.qmd
            - ./rest-api/poet.qmd
            - ./rest-api/embeddings.qmd  
      - section: "Resources"
        contents:
            - ./resources/faq.md
            - ./resources/publications.md
            - ./resources/glossary.md
            - ./resources/site-index.md

format:
  html:
    theme:
      light: [cosmo, theme.scss]
    toc: true
    grid:
      sidebar-width: 350px
      body-width: 900px
      margin-width: 300px