project:
  type: website
  preview: 
    port: 5001

website:
  google-analytics: "G-SS7ET8W19C"
  favicon: './shared/favicon.svg'
  search:
    location: sidebar
    type: textbox
  navbar:
    background: '#F0F3F5'
    logo: './shared/logo.png'
    search: false
    left:
      - text: "Getting Started"
        file: ./getting-started/introduction-page.md
      - text: "Using the App"
        file: ./app/dataset-page.md
      - text: "Walkthroughs"
        file: ./walkthroughs/demo-datasets-page.md
      - text: "REST API docs"
        file: ./rest-api/overview.qmd
      - text: "Python API docs"
        href: https://docs.openprotein.ai/api-python/index.html
  sidebar:
    - id: main
      background: '#F0F3F5'
      style: "docked"
      collapse-level: 2
      align: left
      contents:
        - text: "Getting Started"
          file: ./getting-started/introduction-page.md
        - text: "Using the App"
          file: ./app/dataset-page.md
        - text: "Walkthroughs"
          file: ./walkthroughs/demo-datasets-page.md
        - text: "REST API docs"
          file: ./rest-api/overview.qmd
        - text: "Python API docs"
          href: https://docs.openprotein.ai/api-python/index.html

    - id: api
      title: "API docs"
      style: "docked"
      collapse-level: 2
      align: left
      contents:
        - ./rest-api/overview.qmd
        - ./rest-api/authentication-and-jobs.qmd
        - ./rest-api/project.qmd
        - ./rest-api/poet.qmd
        - ./rest-api/embeddings.qmd

    - id: getting-started
      title: "Getting Started"
      style: "docked"
      collapse-level: 2
      align: left
      contents:
        - ./getting-started/introduction-page.md
        - ./getting-started/account-page.md

    - id: walkthroughs
      title: "Walkthroughs"
      style: "docked"
      collapse-level: 2
      align: left
      contents:
        - ./walkthroughs/demo-datasets-page.md
        - ./walkthroughs/mutagenesis-page.md
        - ./walkthroughs/poet-tutorial-page.md
        - ./walkthroughs/poet-thiolase-codehidden.ipynb

    - id: app
      title: "Using the App"
      style: "docked"
      collapse-level: 2
      align: left
      contents:
        - section: Project
          contents:
          - section: "Dataset"
            contents:
            - ./app/dataset-page.md
            - ./app/visualizations-page.md
          - ./app/predictions-page.md
          - section: "Design"
            contents:
            - ./app/project-design-objectives.md
            - ./app/design-page.md
            - ./app/reference-sequence.md
            - ./app/library-page.md
          - section: Models
            contents:
              - ./app/models-page.md
              - ./app/cross-validation-page.md
        - section: PoET
          contents:
            - ./app/poet-introduction-page.md
            - ./app/poet-defining-prompts-page.md
            - ./app/poet-tools-page.md
        - ./app/structure-prediction.md
        - ./app/job-status-page.md

format:
  html:
    theme:
      light: [cosmo, theme.scss]
    toc: true
    grid:
      sidebar-width: 330px
      body-width: 900px
      margin-width: 300px