project:
  type: website

website:
  favicon: favicon.svg
  sidebar:
    logo: 'logo.svg'
    style: "docked"
    search: true
    contents:
      - section: "Basics"
        contents:
          - introduction-page.md
          - account-page.md
      - section: "Project"
        contents:
          - dataset-page.md
          - visualizations-page.md
          - job-status-page.md
          - predictions-page.md
          - design-page.md
          - library-page.md
      - section: "Models"
        contents:
          - models-page.md
          - cross-validation-page.md
      - section: "Walkthroughs"
        contents:
          - demo-datasets-page.md
          - mutagenesis-page.md
      - section: "PoET"
        contents:
          - poet-introduction-page.md
          - poet-defining-prompts-page.md
          - poet-tools-page.md
          - poet-tutorial-page.md
          - poet-thiolase-codehidden.ipynb

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



