project:
  type: website
  preview: 
    port: 5001

website:
  favicon: './shared/favicon.svg'
  sidebar:
    logo: './shared/logo.svg'
    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - section: Getting Started
        contents:
          - introduction-page.md
          - account-page.md
      - section: Using the App
        contents:
          - section: Project
            contents:
            - section: "Dataset"
              contents:
              - dataset-page.md
              - visualizations-page.md
            - predictions-page.md
            - section: "Design"
              contents:
              - design-page.md
              - library-page.md
            - section: Models
              contents:
                - models-page.md
                - cross-validation-page.md
          - section: PoET
            contents:
              - poet-introduction-page.md
              - poet-defining-prompts-page.md
              - poet-tools-page.md
          - job-status-page.md
      - section: "Walkthroughs"
        contents:
          - demo-datasets-page.md
          - mutagenesis-page.md
          - poet-tutorial-page.md
          - poet-thiolase-codehidden.ipynb
      - section: "Python package"
        contents: 
          - contents:
            - 'python-package/index.qmd'
            - python-package/base.APISession.qmd
            section: Overview
          - contents:
            - python-package/api.data.DataAPI.qmd
            - python-package/api.data.AssayDataset.qmd
            section: Assay Data
          - contents:
            - python-package/api.train.TrainingAPI.qmd
            - python-package/api.train.TrainFuture.qmd
            section: Train
          - contents:
            - python-package/api.design.DesignAPI.qmd
            - python-package/api.design.DesignFuture.qmd
            section: Design
          - contents:
            - python-package/api.predict.PredictAPI.qmd
            - python-package/api.predict.PredictFuture.qmd
            section: Predict
          - contents:
            - python-package/api.poet.PoetAPI.qmd
            - python-package/api.poet.PoetScoreFuture.qmd
            - python-package/api.poet.PoetSingleSiteFuture.qmd
            - python-package/api.poet.PoetGenerateFuture.qmd
            - python-package/api.poet.PromptFuture.qmd
            - python-package/api.poet.MSAFuture.qmd
            section: Protein Evolutionary Transformer (PoET)
          - contents:
            - python-package/api.embedding.EmbeddingAPI.qmd
            - python-package/api.embedding.EmbeddingResultFuture.qmd
            - python-package/api.embedding.ProtembedModel.qmd
            - python-package/api.embedding.SVDModel.qmd
            section: Embeddings
          - python-package/core_demo.ipynb
      - section: "API docs"
        contents:
          - api-overview.qmd
          - api-authentication-and-jobs.qmd
          - api-project.qmd
          - api-poet.qmd
          - api-embeddings.qmd
    

format:
  html:
    theme: cosmo
    toc: true