project:
  type: website

website:
  title: Open protein
  sidebar:
    logo: 'logo.svg'
    style: "docked"
    search: true
    contents:
      - section: "Basics"
        contents:
          - introduction-page.qmd
          - account-page.qmd
      - section: "Project"
        contents:
          - dataset-page.qmd
          - visualizations-page.qmd
          - job-status-page.qmd
          - predictions-page.qmd
          - design-page.qmd
          - library-page.qmd
      - section: "Walkthroughs"
        contents:
          - demo-datasets-page.qmd
          - mutagenesis-page.qmd
      - section: "Prots2prot"
        contents:
          - prots2prot-tutorial-page.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



