---
title: Overview - API docs
---
Welcome to the API suite! 

This documentation hub contains all the information needed to get started with our Projects, PoET and embeddings workflows.

After understanding our workflow offerings, we recommend reading our [Authentication and Jobs](./api-authentication-and-jobs.qmd) guide, as this contains fundamental information on API authorization and our asynchronous job API structure. Afterwhich, we recommend proceeding directly to the respective workflow pages - [Projects](./api-project.qmd), [PoET](./api-poet.qmd), [Embeddings](./api-embeddings.qmd).

## Authentication and Jobs
This section contains the steps for user authentication as well as the endpoints for jobs. On top of login instructions, we describe how our job system is designed and how jobs can be tracked. 

The endpoints include:

  * Login
  * Jobs

## Projects 
This section includes endpoints for tasks under ‘Projects’ which enables analyzing datasets, training sequence-to-function prediction models, using those models to predict properties for new sequences, and designing optimized libraries of sequence variants.

The endpoints include: 

  * Assaydata
  * Train
  * Predict
  * Design
  * Jobs
  * Embeddings

## PoET
This section includes the endpoints for tasks under ‘PoET’ where users can design protein sequences de novo, without functional measurements of the protein of interest. Here, users can generate single substitution, combinatorial variant libraries, or a bespoke high-diversity library.

The endpoints include: 

  * Align
  * PoET

## Embeddings 
This section includes the endpoints for calculating raw embeddings on protein sequences using a number of proprietary and open-source models. 

The endpoints include:

* Embeddings 
* Svd

## Next steps
To start accessing our suite of APIs, refer to these articles to get started: 

* [How to login](./api-authentication-and-jobs.qmd#login)
* [Jobs tracking](./api-authentication-and-jobs.qmd#navigating-the-job-system)
* [Starting a project](./api-project.qmd)


