---
format:
  html:
    code-fold: true
---

# Demo datasets

## Aliphatic amidase (AMIE_PSEAE)

This dataset is a single mutation site saturating dataset from
[Wrenbeck et al.](https://doi.org/10.1038/ncomms15695){target="_blank"} containing
activity measurements for enzyme variants against three different
substrates. The parent sequence is AMIE_PSEAE (UniProt identifier
P11436).

6,819 entries with 3 properties.
[Download](https://drive.google.com/uc?export=download&id=1VteqroPbm2iJl2osfm5-uEZW-9m4WUyM)

## Antibody heavy chain (14H)

This dataset contains binding affinity measurements to the target for a
random mutagenesis library containing single, double, and triple mutants
of an antibody heavy chain variable region from [Li et al.](https://doi.org/10.1101/2022.10.07.502662){target="_blank"}. Mutations were limited to
CDRs 1, 2, and 3. Measurements are log base 10 of the binding Kd in nM.

7,476 entries with 1 property.
[Download](https://drive.google.com/uc?export=download&id=1L4AeuW50EKFKczxLf_YCUM4lC370eNqe)

## Antibody light chain (14L)

This dataset contains binding affinity measurements to the target for a
random mutagenesis library containing single, double, and triple mutants
of an antibody light chain variable region from [Li et
al.](https://doi.org/10.1101/2022.10.07.502662){target="_blank"}. Mutations were limited
to CDRs 1, 2, and 3. Measurements are log base 10 of the binding Kd in
nM.

14,339 entries with 1 property. [Download](https://drive.google.com/uc?export=download&id=17fbByoS2pF6_e8xAVdMNcIF1gifaEzd2)

## Aminoglycoside 3\'-phosphotransferase (KKA2_KLEPN)

This is a single mutation site saturating dataset from [Melnikov et
al.](https://doi.org/10.1093/nar/gku511){target="_blank"} containing measurements of E.
coli growth in the presence of six different antibiotics. This protein
is a kinase that confers antibiotic resistance, hence, growth measures
the activity of the kinase on these antibiotic substrates. The parent
sequence is KKA2_KLEPN (UniProt identifier P00552)

5,279 entries with 6 properties.
[Download](https://drive.google.com/uc?export=download&id=1UE0Lx9EP3tcgpFeduSrFNysBo9rX_rgT)