---
title: Overview - API docs
---
Welcome to the API suite! 

This documentation hub contains all the information needed to get started with our Projects, PoET and embeddings workflows.

After understanding our workflow offerings, we recommend reading our [Authentication and Jobs](./authentication-and-jobs.qmd) guide, as this contains fundamental information on API authorization and our asynchronous job API structure. Afterwhich, we recommend proceeding directly to the respective workflow pages - [Projects](./project.qmd), [PoET](./poet.qmd), [Embeddings](./embeddings.qmd).

Another method for interacting with our API is by using our Python API. Find out more [here](https://docs.openprotein.ai/api-python/index.html).

## Authentication and Jobs
Check out the steps for user authentication as well as the endpoints for jobs. On top of login instructions, we describe how our job system is designed and how jobs can be tracked. 

The endpoints include:

  * Login
  * Jobs

## Projects 
Kickoff your projects by using the endpoints to enable analyzing datasets, training sequence-to-function prediction models, using those models to predict properties for new sequences, and designing optimized libraries of sequence variants.

The endpoints include: 

  * Assaydata
  * Train
  * Predict
  * Design
  * Jobs
  * Embeddings

## PoET
Design de novo sequences using these endpoints, without functional measurements of the protein of interest. Our proprietary models enable generation of single substitution, combinatorial variant libraries, or a high-diversity library. 

The endpoints include: 

  * Align
  * PoET

## Embeddings 
Learn more about the endpoints needed to calculate raw embeddings on protein sequences here! Our platform offers a range of endpoints that harness the power of both our proprietary and open-source models.

The endpoints include:

* Embeddings 
* Svd

## Next steps
To start accessing our suite of APIs, refer to these articles to get started: 

* [How to login](./authentication-and-jobs.qmd#login)
* [Jobs tracking](./authentication-and-jobs.qmd#navigating-the-job-system)
* [Starting a project](./project.qmd)